# Generated by Django 2.0.6 on 2018-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaccount',
            name='hotp_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteaccount',
            name='hotp_key',
            field=models.CharField(default='ZLIY5B2VRRKD6RJY', max_length=20),
        ),
    ]
