# Generated by Django 2.0.6 on 2018-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180611_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaccount',
            name='hotp_iteration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='siteaccount',
            name='hotp_key',
            field=models.CharField(default='TQVX2KVNFLKAHYNT', max_length=20),
        ),
    ]
